//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlExamples {
    
    
    public partial class _default {
        
        /// <summary>
        /// tb00 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.textbox tb00;
        
        /// <summary>
        /// tbregex00 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.textbox tbregex00;
        
        /// <summary>
        /// dl00 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.dropdownlist dl00;
        
        /// <summary>
        /// rbl00 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.radiobuttonlist rbl00;
        
        /// <summary>
        /// cbl00 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.checkboxlist cbl00;
        
        /// <summary>
        /// textA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.textbox textA;
        
        /// <summary>
        /// b00 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.button b00;
        
        /// <summary>
        /// cbl01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.checkboxlist cbl01;
        
        /// <summary>
        /// rbl01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.radiobuttonlist rbl01;
        
        /// <summary>
        /// cbcb01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.checkbox cbcb01;
        
        /// <summary>
        /// db0000 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.datebox db0000;
        
        /// <summary>
        /// b01 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::kuujinbo.asp.net.WebForms.controls.button b01;
    }
}
